// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_absentee_periode")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpAbsenteePeriode
{
    [Key]
    [Column("periode_id")]
    [StringLength(21)]
    public string PeriodeId { get; set; }

    [Required]
    [Column("year")]
    [StringLength(4)]
    public string Year { get; set; }

    [Required]
    [Column("month")]
    [StringLength(2)]
    public string Month { get; set; }

    /// <summary>
    /// 1: available; 99: closing
    /// </summary>
    [Column("status", TypeName = "mediumint")]
    public int Status { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_etr_closing", TypeName = "datetime")]
    public DateTime DtEtrClosing { get; set; }

    [Required]
    [Column("user_etr_closing")]
    [StringLength(21)]
    public string? UserEtrClosing { get; set; }
}