// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_absent_old")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpAbsentOld
{
    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("employee_name")]
    [StringLength(100)]
    public string EmployeeName { get; set; }

    [Column("absent_date")]
    public DateOnly AbsentDate { get; set; }

    [Required]
    [Column("time_in")]
    [StringLength(8)]
    public string TimeIn { get; set; }

    [Required]
    [Column("time_out")]
    [StringLength(8)]
    public string TimeOut { get; set; }

    [Column("etr_dt", TypeName = "datetime")]
    public DateTime EtrDt { get; set; }
}