// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models.Database.MySql.Support;

[PrimaryKey("EmployeeId", "AbsentDate")]
[Table("tp_absent_no_card")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpAbsentNoCard
{
    [Key]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

   
    [Column("absent_date")]
    public DateTime AbsentDate { get; set; }

   

    [Required]
    [Column("file_name")]
    [StringLength(200)]
    public string FileName { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }
 
}