// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_absent_revisi")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpAbsentRevisi
{
    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("absent_date")]
    public DateOnly AbsentDate { get; set; }

    [Required]
    [Column("category")]
    [StringLength(21)]
    public string Category { get; set; }

    [Required]
    [Column("type_revisi")]
    [StringLength(21)]
    public string TypeRevisi { get; set; }

    [Required]
    [Column("request_by")]
    [StringLength(21)]
    public string RequestBy { get; set; }

    [Required]
    [Column("reason")]
    [StringLength(250)]
    public string Reason { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Required]
    [Column("type")]
    [StringLength(25)]
    public string Type { get; set; }

    [Column("size")]
    public int Size { get; set; }

    [Required]
    [Column("approve_by")]
    [StringLength(21)]
    public string ApproveBy { get; set; }

    [Column("approve_date")]
    public DateOnly ApproveDate { get; set; }

    /// <summary>
    /// 1=ready entry, -1 =reject; 5=adknowledge; 9=clear;
    /// </summary>
    [Column("status")]
    public bool Status { get; set; }
}