// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_absent_foto")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpAbsentFoto
{
    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("absent_date")]
    public DateOnly AbsentDate { get; set; }

    [Required]
    [Column("time_in")]
    [StringLength(8)]
    public string TimeIn { get; set; }

    [Required]
    [Column("time_out")]
    [StringLength(8)]
    public string TimeOut { get; set; }

    [Required]
    [Column("file_name_in")]
    [StringLength(100)]
    public string FileNameIn { get; set; }

    [Required]
    [Column("file_name_out")]
    [StringLength(100)]
    public string FileNameOut { get; set; }
}