// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_cuti")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpCuti
{
    [Key]
    [Column("cuti_id")]
    [StringLength(21)]
    public string CutiId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("keperluan")]
    [StringLength(100)]
    public string Keperluan { get; set; }

    [Required]
    [Column("type_cuti_id")]
    [StringLength(21)]
    public string TypeCutiId { get; set; }

    [Column("request_date")]
    public DateTime RequestDate { get; set; }

    [Column("jumlah_cuti")]
    public float JumlahCuti { get; set; }

    [Column("is_read")]
    public sbyte IsRead { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Required]
    [Column("approve_by")]
    [StringLength(21)]
    public string ApproveBy { get; set; }

    [Column("approve_date")]
    public DateTime ApproveDate { get; set; }

    [Required]
    [Column("noted")]
    [StringLength(150)]
    public string Noted { get; set; }

    //penambahan 
    [Column("deleted_at", TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [Column("is_notify")]
    public int IsNotify { get; set; }

    [Column("updated_by")]
    [StringLength(21)]
    public string? UpdatedBy { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("deleted_by")]
    [StringLength(21)]
    public string? DeletedBy { get; set; }

    [Required]
    [Column("created_by")]
    [StringLength(21)]
    public string CreatedBy { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }
}