// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_datainventory")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpDatainventory
{
    [Column("item_id")]
    public int ItemId { get; set; }

    [Required]
    [Column("item_name")]
    [StringLength(50)]
    public string ItemName { get; set; }

    [Column("item_qty")]
    public int ItemQty { get; set; }

    [Column("item_price")]
    public int ItemPrice { get; set; }

    [Required]
    [Column("inventory_id")]
    [StringLength(20)]
    public string InventoryId { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}