// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_detail_cuti")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpDetailCuti
{
    [Required]
    [Column("id_detail_cuti")]
    [StringLength(21)]
    public string IdDetailCuti { get; set; }

    [Required]
    [Column("cuti_id")]
    [StringLength(21)]
    public string CutiId { get; set; }

    [Column("cuti_date")]
    public DateOnly CutiDate { get; set; }

    [Column("qty")]
    public float Qty { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}