// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_employee_affair_document")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpEmployeeAffairDocument
{
    [Key]
    [Column("id")]
    [StringLength(15)]
    public string Id { get; set; }

    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    /// <summary>
    /// CT000 artinya dokumen umum
    /// </summary>
    [Column("claim_type_id")]
    [StringLength(21)]
    public string ClaimTypeId { get; set; }

    [Required]
    [Column("document_id")]
    [StringLength(11)]
    public string DocumentId { get; set; }

    /// <summary>
    /// 0, tidak ada1, ada
    /// </summary>
    [Column("document_status")]
    public byte DocumentStatus { get; set; }

    [Column("fc_document")]
    public int? FcDocument { get; set; }

    [Column("file_name")]
    [StringLength(100)]
    public string FileName { get; set; }

    [Column("size")]
    public long Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }

    [Column("submitted", TypeName = "datetime")]
    public DateTime? Submitted { get; set; }

    [Column("submitted_by")]
    [StringLength(21)]
    public string SubmittedBy { get; set; }

    [Column("is_deleted")]
    public int IsDeleted { get; set; }
}