// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_employee_relation")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpEmployeeRelation
{
    [Key]
    [Column("relation_id")]
    [StringLength(21)]
    public string RelationId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("hubungan_id")]
    [StringLength(21)]
    public string HubunganId { get; set; }

    [Required]
    [Column("relation_name")]
    [StringLength(100)]
    public string RelationName { get; set; }

    [Required]
    [Column("relation_alamat")]
    [StringLength(150)]
    public string RelationAlamat { get; set; }

    [Required]
    [Column("no_telp")]
    [StringLength(30)]
    public string NoTelp { get; set; }

    [Column("status")]
    public int Status { get; set; }
}