// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_employee_studi")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpEmployeeStudi
{
    [Key]
    [Column("pendidikan_id")]
    [StringLength(21)]
    public string PendidikanId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("type_ins_id")]
    [StringLength(20)]
    public string TypeInsId { get; set; }

    [Required]
    [Column("studi_id")]
    [StringLength(21)]
    public string StudiId { get; set; }

    [Required]
    [Column("school_name")]
    [StringLength(100)]
    public string SchoolName { get; set; }

    [Column("periode")]
    public DateTime Periode { get; set; }

    [Column("akhir")]
    public DateTime Akhir { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column("size")]
    public long Size { get; set; }

    [Required]
    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }
}