// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_employee_license")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpEmployeeLicense
{
    [Key]
    [Column("license_id")]
    [StringLength(21)]
    public string LicenseId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("type_ins_id")]
    [StringLength(20)]
    public string TypeInsId { get; set; }

    [Required]
    [Column("license_name")]
    [StringLength(100)]
    public string LicenseName { get; set; }

    [Required]
    [Column("periode")]
    [StringLength(25)]
    public string Periode { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column("size")]
    public long Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }
}