// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_extend")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpExtend
{
    [Key]
    [Column("extend_id")]
    [StringLength(5)]
    public string ExtendId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(25)]
    public string EmployeeId { get; set; }

    [Column("start_extend_date")]
    public DateTime StartExtendDate { get; set; }

    [Column("end_extend_date")]
    public DateTime EndExtendDate { get; set; }

    [Required]
    [Column("reason")]
    [StringLength(100)]
    public string Reason { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(100)]
    public string FileName { get; set; }

    [Required]
    [Column("type")]
    [StringLength(15)]
    public string Type { get; set; }

    [Column("size")]
    public long Size { get; set; }

    [Column("status")]
    public int Status { get; set; }
}