// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_frq_it_service")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpFrqItService
{
    [Required]
    [Column("request_id")]
    [StringLength(21)]
    public string RequestId { get; set; }

    [Column("request_date", TypeName = "datetime")]
    public DateTime? RequestDate { get; set; }

    [Column("category_type")]
    public sbyte CategoryType { get; set; }

    [Column("user_id")]
    [StringLength(21)]
    public string UserId { get; set; }

    [Column("phone_number")]
    [StringLength(25)]
    public string PhoneNumber { get; set; }

    [Column("outlet_id")]
    [StringLength(21)]
    public string OutletId { get; set; }

    [Required]
    [Column("application_id")]
    [StringLength(21)]
    public string ApplicationId { get; set; }

    [Column("problem_id")]
    [StringLength(21)]
    public string ProblemId { get; set; }

    [Column("problem_description")]
    [StringLength(3000)]
    public string ProblemDescription { get; set; }

    [Column("priority_level")]
    public sbyte? PriorityLevel { get; set; }

    [Column("reject_reason")]
    [StringLength(256)]
    public string RejectReason { get; set; }

    [Column("progress_status")]
    public int? ProgressStatus { get; set; }

    /// <summary>
    /// -1=reject;0=delete;1=done;100=need approval
    /// </summary>
    [Column("status")]
    public short Status { get; set; }

    [Column("user_id_assigned")]
    [StringLength(21)]
    public string UserIdAssigned { get; set; }

    [Column("assigned_date", TypeName = "datetime")]
    public DateTime? AssignedDate { get; set; }

    [Column("user_id_approved")]
    [StringLength(21)]
    public string UserIdApproved { get; set; }

    [Column("approved_date", TypeName = "datetime")]
    public DateTime? ApprovedDate { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime? DtEtr { get; set; }

    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }
}