// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_frq_it_service_task")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpFrqItServiceTask
{
    [Required]
    [Column("request_id_detail")]
    [StringLength(21)]
    public string RequestIdDetail { get; set; }

    [Required]
    [Column("request_id")]
    [StringLength(21)]
    public string RequestId { get; set; }

    [Required]
    [Column("caused_by")]
    [StringLength(5000)]
    public string CausedBy { get; set; }

    [Required]
    [Column("task_description")]
    [StringLength(5000)]
    public string TaskDescription { get; set; }

    [Required]
    [Column("close_by_user_id")]
    [StringLength(21)]
    public string CloseByUserId { get; set; }

    [Column("close_date", TypeName = "datetime")]
    public DateTime? CloseDate { get; set; }

    [Column("progress_status")]
    public int ProgressStatus { get; set; }
}