// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_history_change_password")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpHistoryChangePassword
{
    [Column("id_history_password")]
    public int IdHistoryPassword { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("password")]
    [StringLength(250)]
    public string Password { get; set; }

    [Column("date_change_password", TypeName = "datetime")]
    public DateTime DateChangePassword { get; set; }
}