// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_incoming_letter")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpIncomingLetter
{
    [Required]
    [Column("letter_id")]
    [StringLength(21)]
    public string LetterId { get; set; }

    [Column("letter_date")]
    public DateOnly LetterDate { get; set; }

    [Required]
    [Column("sender")]
    [StringLength(200)]
    public string Sender { get; set; }

    [Required]
    [Column("destination_id")]
    [StringLength(21)]
    public string DestinationId { get; set; }

    [Column("remark")]
    [StringLength(100)]
    public string Remark { get; set; }

    [Column("subject")]
    [StringLength(200)]
    public string Subject { get; set; }

    [Required]
    [Column("status")]
    public bool? Status { get; set; }

    [Column("receipt_id")]
    [StringLength(21)]
    public string ReceiptId { get; set; }

    [Column("receipt_dt")]
    public DateOnly? ReceiptDt { get; set; }

    [Column("is_accepted")]
    public sbyte IsAccepted { get; set; }

    [Column("accepted_dt", TypeName = "datetime")]
    public DateTime? AcceptedDt { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }
}