// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_notification_topic")]
public partial class TpNotificationTopic
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("topic")]
    [StringLength(100)]
    public string Topic { get; set; }

    [Required]
    [Column("employeeId")]
    [StringLength(100)]
    public string EmployeeId { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Column("is_main")]
    public int IsMain { get; set; }
}