// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_notification_traffic")]
[Index("Id", Name = "id_UNIQUE", IsUnique = true)]
public partial class TpNotificationTraffic
{
    [Key]
    [Column("id")]
    [StringLength(20)]
    public string Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(200)]
    public string Title { get; set; }

    [Required]
    [Column("notification")]
    [StringLength(250)]
    public string Notification { get; set; }

    [Required]
    [Column("topic")]
    [StringLength(45)]
    public string Topic { get; set; }

    [Column("send_at", TypeName = "datetime")]
    public DateTime? SendAt { get; set; }

    [Required]
    [Column("sender")]
    [StringLength(45)]
    public string Sender { get; set; }

    [Required]
    [Column("destination")]
    [StringLength(45)]
    public string Destination { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }
}