// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_outgoing_letter")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpOutgoingLetter
{
    [Key]
    [Column("letter_id")]
    [StringLength(21)]
    public string LetterId { get; set; }

    [Column("letter_date")]
    public DateOnly LetterDate { get; set; }

    [Required]
    [Column("letter_form_id")]
    [StringLength(21)]
    public string LetterFormId { get; set; }

    [Column("mapping_id")]
    [StringLength(35)]
    public string MappingId { get; set; }

    [Column("checking")]
    public sbyte Checking { get; set; }

    [Required]
    [Column("letter_type_id")]
    [StringLength(21)]
    public string LetterTypeId { get; set; }

    [Required]
    [Column("letter_number")]
    [StringLength(6)]
    public string LetterNumber { get; set; }

    [Required]
    [Column("department_id")]
    [StringLength(21)]
    public string DepartmentId { get; set; }

    /// <summary>
    /// title_id
    /// </summary>
    [Required]
    [Column("signature_by")]
    [StringLength(21)]
    public string SignatureBy { get; set; }

    [Required]
    [Column("letter_format_number")]
    [StringLength(50)]
    public string LetterFormatNumber { get; set; }

    [Required]
    [Column("destination")]
    [StringLength(200)]
    public string Destination { get; set; }

    [Column("remark")]
    [StringLength(200)]
    public string Remark { get; set; }

    [Required]
    [Column("tender")]
    [StringLength(100)]
    public string Tender { get; set; }

    [Column("cob_id")]
    [StringLength(21)]
    public string CobId { get; set; }

    [Column("security_id")]
    [StringLength(21)]
    public string SecurityId { get; set; }

    [Column("document_status")]
    public sbyte DocumentStatus { get; set; }

    [Column("file_name")]
    [StringLength(50)]
    public string FileName { get; set; }

    [Column("size")]
    public int? Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }

    [Required]
    [Column("status")]
    public bool? Status { get; set; }

    /// <summary>
    /// pengantar
    /// </summary>
    [Column("user_sender")]
    [StringLength(21)]
    public string UserSender { get; set; }

    [Column("receipt_by")]
    [StringLength(30)]
    public string ReceiptBy { get; set; }

    [Column("receipt_dt")]
    public DateOnly? ReceiptDt { get; set; }

    [Column("is_accepted")]
    public sbyte IsAccepted { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }
}