// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models.Database.MySql.View
{
    [Table("tp_permission_detail")]
    [MySqlCharSet("latin1")]
    [MySqlCollation("latin1_swedish_ci")]
    public partial class TpPermissionDetail
    {
        [Key]
        [Column("permission_detail_id")]
        [StringLength(21)]
        public string PermissionDetailId { get; set; }
        [Required]
        [Column("permission_id")]
        [StringLength(21)]
        public string PermissionId { get; set; }
        [Column("permission_date")]
        public DateTime PermissionDate { get; set; }
        [Column("status")]
        public int Status { get; set; }
    }
}