// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models.Database.MySql.View
{
    [Table("tp_permission")]
    [MySqlCharSet("latin1")]
    [MySqlCollation("latin1_swedish_ci")]
    public partial class TpPermission
    {
        [Key]
        [Column("permission_id")]
        [StringLength(21)]
        public string PermissionId { get; set; }
        [Required]
        [Column("employee_id")]
        [StringLength(21)]
        public string EmployeeId { get; set; }
        [Required]
        [Column("reason")]
        [StringLength(100)]
        public string Reason { get; set; }
        [Required]
        [Column("permission_type_id")]
        [StringLength(21)]
        public string PermissionTypeId { get; set; }
        [Column("request_date")]
        public DateTime RequestDate { get; set; }
        [Column("is_read", TypeName = "tinyint(4)")]
        public sbyte IsRead { get; set; }
        [Column("status")]
        public int Status { get; set; }


        [Column("file_name")]
        [StringLength(255)]
        public string? FileName { get; set; }

        [Column("type")]
        [StringLength(25)]
        public string? Type { get; set; }

        [Column("size")]
        public int? Size { get; set; }

        [Column("approve_by")]
        [StringLength(21)]
        public string? ApproveBy { get; set; }
        [Column("approve_date")]
        public DateTime? ApproveDate { get; set; }
        [Required]
        [Column("noted")]
        [StringLength(150)]
        public string? Noted { get; set; }
        [Column("is_notify", TypeName = "int(1)")]
        public int IsNotify { get; set; }
        [Column("is_cut_absent", TypeName = "tinyint(4)")]
        public sbyte IsCutAbsent { get; set; }
        [Column("cut_absent")]
        public float CutAbsent { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }
        [Required]
        [Column("created_by")]
        [StringLength(15)]
        public string CreatedBy { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }
        [Column("updated_by")]
        [StringLength(15)]
        public string? UpdatedBy { get; set; }
        [Column("deleted_at", TypeName = "datetime")]
        public DateTime? DeletedAt { get; set; }
        [Column("deleted_by")]
        [StringLength(15)]
        public string? DeletedBy { get; set; }
    }
}