// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_replacement_detail")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]

public partial class TpReplacementDetail
{
    [Key]
    [Column("id")]
    [StringLength(25)]
    public string Id { get; set; }

    [Required]
    [Column("replacement_id")]
    [StringLength(25)]
    public string ReplacementId { get; set; }

    [Column("replacement_date")]
    public DateTime ReplacementDate { get; set; }
}
