// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_reimbursment")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpReimbursment
{
    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("years_of_reimbursment")]
    [StringLength(4)]
    public string YearsOfReimbursment { get; set; }

    [Column("date_of_reimbursment")]
    public DateOnly DateOfReimbursment { get; set; }

    [Column("amount_reimbursment")]
    [Precision(10, 0)]
    public decimal AmountReimbursment { get; set; }

    [Column("deskripsi")]
    public int Deskripsi { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}