// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_request")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpRequest
{
    [Key]
    [Column("request_id")]
    [StringLength(5)]
    public string RequestId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("request_date")]
    public DateOnly RequestDate { get; set; }

    [Required]
    [Column("time_start")]
    [StringLength(20)]
    public string TimeStart { get; set; }

    [Required]
    [Column("time_end")]
    [StringLength(20)]
    public string TimeEnd { get; set; }

    [Required]
    [Column("total_overtime")]
    [StringLength(20)]
    public string TotalOvertime { get; set; }

    [Column("cut_absent")]
    public float CutAbsent { get; set; }

    [Required]
    [Column("keperluan")]
    [StringLength(100)]
    public string Keperluan { get; set; }

    [Required]
    [Column("request_type_id")]
    [StringLength(10)]
    public string RequestTypeId { get; set; }

    [Column("is_read")]
    public sbyte IsRead { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("approve_by")]
    [StringLength(20)]
    public string ApproveBy { get; set; }

    [Column("noted")]
    [StringLength(150)]
    public string Noted { get; set; }
}