// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_replacement_leave")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]

public partial class TpReplacementLeave
{
    [Key]
    [Column("replacement_id")]
    [StringLength(21)]
    public string ReplacementId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(25)]
    public string EmployeeId { get; set; }

    [Column("request_date")]
    public DateTime RequestDate { get; set; }

    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("approve_by")]
    [StringLength(21)]
    public string ApproveBy { get; set; }

    [Column("approve_date")]
    public DateTime ApproveDate { get; set; }

    [Column("approve_status")]
    public int ApproveStatus { get; set; }

    [Column("approve_reason")]
    [StringLength(255)]
    public string ApproveReason { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [Column("created_by")]
    [StringLength(21)]
    public string CreatedBy { get; set; }

    [Column("updated_at")]
    public DateTime? UpdatedAt { get; set; }

    [Column("updated_by")]
    [StringLength(21)]
    public string? UpdatedBy { get; set; }

    [Column("deleted_at")]
    public DateTime? DeletedAt { get; set; }

    [Column("deleted_by")]
    [StringLength(21)]
    public string? DeletedBy { get; set; }

}
