// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tp_termination")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpTermination
{
    [Key]
    [Column("termination_id")]
    [StringLength(5)]
    public string TerminationId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("termination_date")]
    public DateTime TerminationDate { get; set; }

    [Required]
    [Column("reason")]
    [StringLength(50)]
    public string Reason { get; set; }

    [Column("reason_id")]
    public byte ReasonId { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("size")]
    public long? Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }
}