// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Keyless]
[Table("tp_upload_file_name")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpUploadFileName
{
    [Required]
    [Column("upload_id")]
    [StringLength(21)]
    public string UploadId { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(50)]
    public string FileName { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }
}