// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models.Database.MySql.Support;

[Table("tp_warning_letter")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TpWarningLetter
{
    [Key]
    [Column("id")]
    [StringLength(21)]
    public string Id { get; set; }

    [Column("number")]
    public int Number { get; set; }

    [Required]
    [Column("caused_by")]
    [StringLength(50)]
    public string CausedBy { get; set; }

    [Column("letter_date")]
    public DateTime LetterDate { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("begin_date")]
    public DateTime BeginDate { get; set; }

    [Column("end_date")]
    public DateTime EndDate { get; set; }

    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [Column("created_by")]
    [StringLength(21)]
    public string CreatedBy { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }

    [Column("updated_by")]
    [StringLength(21)]
    public string UpdatedBy { get; set; }

    [Column("deleted_at")]
    public DateTime DeletedAt { get; set; }

    [Column("deleted_by")]
    [StringLength(21)]
    public string DeletedBy { get; set;}

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("size")]
    public long? Size { get; set; }

    [Column("type")]
    [StringLength(255)]
    public string Type { get; set; }
}