// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_bank")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmBank
{
    [Key]
    [Column("bank_id")]
    [StringLength(21)]
    public string BankId { get; set; }

    [Required]
    [Column("parent_id")]
    [StringLength(21)]
    public string ParentId { get; set; }

    [Required]
    [Column("bank_name")]
    [StringLength(50)]
    public string BankName { get; set; }

    [Required]
    [Column("address")]
    [StringLength(255)]
    public string Address { get; set; }

    [Required]
    [Column("telp")]
    [StringLength(100)]
    public string Telp { get; set; }

    [Required]
    [Column("fax")]
    [StringLength(100)]
    public string Fax { get; set; }

    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }
}