// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tp_transaction")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTpTransaction
{
    [Key]
    [Column("transaction_id")]
    [StringLength(21)]
    public string TransactionId { get; set; }

    [Required]
    [Column("product_id")]
    [StringLength(21)]
    public string ProductId { get; set; }

    [Required]
    [Column("insurance_id")]
    [StringLength(21)]
    public string InsuranceId { get; set; }

    [Required]
    [Column("bank_id")]
    [StringLength(21)]
    public string BankId { get; set; }

    [Column("reference_number")]
    [StringLength(50)]
    public string ReferenceNumber { get; set; }

    [Required]
    [Column("customer_name")]
    [StringLength(100)]
    public string CustomerName { get; set; }

    [Column("date_of_birth")]
    public DateOnly DateOfBirth { get; set; }

    [Column("credit_begin_date")]
    public DateOnly CreditBeginDate { get; set; }

    [Column("credit_end_date")]
    public DateOnly CreditEndDate { get; set; }

    [Required]
    [Column("range_time_id")]
    [StringLength(21)]
    public string RangeTimeId { get; set; }

    [Column("coverage")]
    [Precision(10, 0)]
    public decimal Coverage { get; set; }

    [Column("rate")]
    public float Rate { get; set; }

    [Column("premium")]
    [Precision(10, 0)]
    public decimal Premium { get; set; }

    [Column("percentage_brokerage")]
    [Precision(10, 4)]
    public decimal PercentageBrokerage { get; set; }

    [Column("percentage_feebase")]
    [Precision(10, 4)]
    public decimal PercentageFeebase { get; set; }

    [Column("brokerage")]
    [Precision(10, 4)]
    public decimal Brokerage { get; set; }

    [Column("premium_net")]
    [Precision(10, 4)]
    public decimal PremiumNet { get; set; }

    [Column("fee_base")]
    [Precision(10, 4)]
    public decimal FeeBase { get; set; }

    [Column("polis_number")]
    [StringLength(100)]
    public string PolisNumber { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }
}