// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tp_claim")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTpClaim
{
    [Key]
    [Column("claim_id")]
    [StringLength(21)]
    public string ClaimId { get; set; }

    [Required]
    [Column("product_id")]
    [StringLength(21)]
    public string ProductId { get; set; }

    [Required]
    [Column("transaction_id")]
    [StringLength(21)]
    public string TransactionId { get; set; }

    [Required]
    [Column("customer_name")]
    [StringLength(100)]
    public string CustomerName { get; set; }

    [Column("date_of_birth")]
    public DateOnly DateOfBirth { get; set; }

    [Column("request_date")]
    public DateOnly RequestDate { get; set; }

    [Required]
    [Column("reference_number")]
    [StringLength(100)]
    public string ReferenceNumber { get; set; }

    [Column("cause_type_id")]
    public short CauseTypeId { get; set; }

    [Column("age_of_death")]
    public int? AgeOfDeath { get; set; }

    [Column("date_of_death")]
    public DateOnly DateOfDeath { get; set; }

    [Column("amount_requested")]
    [Precision(10, 0)]
    public decimal AmountRequested { get; set; }

    [Column("acceptance_date")]
    public DateOnly AcceptanceDate { get; set; }

    [Column("amount_received")]
    [Precision(10, 0)]
    public decimal AmountReceived { get; set; }

    /// <summary>
    /// 1=menunggu verifikator; 5= menuggu aproval; 10: menunggu pembayaran;25=sudah dibayar;55=pending Verifikasi;-2=reject from verifikator; -1= reject
    /// </summary>
    [Column("status")]
    public short Status { get; set; }

    [Required]
    [Column("reason")]
    [StringLength(255)]
    public string Reason { get; set; }

    [Column("is_deleted")]
    public sbyte IsDeleted { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("verified_by")]
    [StringLength(21)]
    public string VerifiedBy { get; set; }

    [Column("verified_dt", TypeName = "datetime")]
    public DateTime? VerifiedDt { get; set; }

    [Column("verified_status")]
    public short VerifiedStatus { get; set; }

    [Column("verified_reason")]
    [StringLength(255)]
    public string VerifiedReason { get; set; }

    [Column("approved_by")]
    [StringLength(21)]
    public string ApprovedBy { get; set; }

    [Column("approved_reason")]
    [StringLength(255)]
    public string ApprovedReason { get; set; }

    [Column("approved_dt", TypeName = "datetime")]
    public DateTime? ApprovedDt { get; set; }

    [Column("paid_by")]
    [StringLength(21)]
    public string PaidBy { get; set; }

    [Column("paid_dt", TypeName = "datetime")]
    public DateTime? PaidDt { get; set; }

    [Column("paid_reference")]
    [StringLength(255)]
    public string PaidReference { get; set; }
}