// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_claim_risk")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmClaimRisk
{
    [Key]
    [Column("risk_id")]
    public int RiskId { get; set; }

    [Column("risk_name")]
    [StringLength(100)]
    public string RiskName { get; set; }

    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }
}