// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tp_claim_document")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTpClaimDocument
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("claim_id")]
    [StringLength(21)]
    public string ClaimId { get; set; }

    /// <summary>
    /// CT000 artinya dokumen umum
    /// </summary>
    [Column("claim_type_id")]
    [StringLength(21)]
    public string ClaimTypeId { get; set; }

    [Column("document_id")]
    public int DocumentId { get; set; }

    /// <summary>
    /// 0, tidak ada1, ada
    /// </summary>
    [Column("document_status")]
    public bool DocumentStatus { get; set; }

    [Column("fc_document")]
    public bool? FcDocument { get; set; }

    [Column("file_name")]
    [StringLength(100)]
    public string FileName { get; set; }

    [Column("size")]
    public int Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }

    [Column("submitted", TypeName = "datetime")]
    public DateTime? Submitted { get; set; }

    [Column("submitted_by")]
    [StringLength(21)]
    public string SubmittedBy { get; set; }

    [Column("is_deleted")]
    public bool IsDeleted { get; set; }
}