// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tp_claim_document_additional")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTpClaimDocumentAdditional
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("claim_id")]
    [StringLength(21)]
    public string ClaimId { get; set; }

    [Column("document_name")]
    [StringLength(100)]
    public string DocumentName { get; set; }

    [Column("file_name")]
    [StringLength(100)]
    public string FileName { get; set; }

    [Column("size")]
    public int? Size { get; set; }

    [Column("type")]
    [StringLength(20)]
    public string Type { get; set; }

    [Column("fc_document")]
    public bool? FcDocument { get; set; }

    [Column("submitted", TypeName = "datetime")]
    public DateTime? Submitted { get; set; }

    [Column("submitted_by")]
    [StringLength(21)]
    public string SubmittedBy { get; set; }

    [Column("is_deleted")]
    public bool? IsDeleted { get; set; }
}