// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_claim_type")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmClaimType
{
    [Key]
    [Column("claim_type_id")]
    [StringLength(21)]
    public string ClaimTypeId { get; set; }

    [Column("risk_id")]
    public int? RiskId { get; set; }

    [Required]
    [Column("product_id")]
    [StringLength(21)]
    public string ProductId { get; set; }

    [Required]
    [Column("claim_type")]
    [StringLength(200)]
    public string ClaimType { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("pasal")]
    [StringLength(10)]
    public string Pasal { get; set; }

    [Column("source")]
    [StringLength(10)]
    public string Source { get; set; }
}