// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_range_time")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmRangeTime
{
    [Key]
    [Column("range_time_id")]
    [StringLength(21)]
    public string RangeTimeId { get; set; }

    [Column("range_time")]
    public int RangeTime { get; set; }

    [Column("rate")]
    public float Rate { get; set; }

    [Column("status")]
    public sbyte Status { get; set; }
}