// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_periode")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmPeriode
{
    [Key]
    [Column("periode_id")]
    [StringLength(21)]
    public string PeriodeId { get; set; }

    [Required]
    [Column("periode_name")]
    [StringLength(4)]
    public string PeriodeName { get; set; }

    [Column("status")]
    public sbyte Status { get; set; }
}