// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("bjb_tm_claim_general_document")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class BjbTmClaimGeneralDocument
{
    [Key]
    [Column("document_id")]
    public int DocumentId { get; set; }

    [Required]
    [Column("document_name")]
    [StringLength(200)]
    public string DocumentName { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("source")]
    [StringLength(10)]
    public string Source { get; set; }

    [Column("debarkasi")]
    public bool Debarkasi { get; set; }

    [Column("is_required")]
    public bool? IsRequired { get; set; }
}