// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("otp_logs")]
public partial class OtpLog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(8)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("status", TypeName = "enum('Pending','Verified','Expire')")]
    public string Status { get; set; }

    [Required]
    [Column("otp")]
    [StringLength(8)]
    public string Otp { get; set; }

    [Column("request_at", TypeName = "datetime")]
    public DateTime RequestAt { get; set; }

    [Column("verified_at", TypeName = "datetime")]
    public DateTime? VerifiedAt { get; set; }

    [Column("expire_at")]
    [StringLength(45)]
    public string ExpireAt { get; set; }
}