// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_application")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmApplication
{
    [Key]
    [Column("application_id")]
    [StringLength(21)]
    public string ApplicationId { get; set; }

    [Column("application_name")]
    [StringLength(50)]
    public string ApplicationName { get; set; }

    [Column("remark")]
    [StringLength(200)]
    public string Remark { get; set; }

    [Column("order_by")]
    public int? OrderBy { get; set; }

    [Column("status")]
    public short Status { get; set; }
}