// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_bank")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmBank
{
    [Key]
    [Column("bank_id")]
    [StringLength(5)]
    public string BankId { get; set; }

    [Required]
    [Column("bank_name")]
    [StringLength(25)]
    public string BankName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}