// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_cob")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmCob
{
    [Key]
    [Column("cob_id")]
    [StringLength(21)]
    public string CobId { get; set; }

    [Required]
    [Column("cob_name")]
    [StringLength(50)]
    public string CobName { get; set; }

    [Column("status")]
    public sbyte Status { get; set; }
}