// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_division_head")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmDivisionHead
{
    [Key]
    [Column("div_id")]
    [StringLength(25)]
    public string DivId { get; set; }

    [Required]
    [Column("department_head_name")]
    [StringLength(50)]
    public string DepartmentHeadName { get; set; }
}