// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_employee_affair_document")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmEmployeeAffairDocument
{
    [Key]
    [Column("document_id")]
    public int DocumentId { get; set; }

    [Required]
    [Column("claim_type_id")]
    [StringLength(21)]
    public string ClaimTypeId { get; set; }

    [Required]
    [Column("document")]
    [StringLength(200)]
    public string Document { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("is_required")]
    public bool? IsRequired { get; set; }
}