// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_employee_backup")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmEmployeeBackup
{
    [Key]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("employee_first_name")]
    [StringLength(50)]
    public string EmployeeFirstName { get; set; }

    [Column("employee_last_name")]
    [StringLength(50)]
    public string EmployeeLastName { get; set; }

    [Required]
    [Column("department_id")]
    [StringLength(21)]
    public string DepartmentId { get; set; }

    [Required]
    [Column("designation_id")]
    [StringLength(21)]
    public string DesignationId { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}