// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_employee_status")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmEmployeeStatus
{
    [Key]
    [Column("employee_status_id")]
    [StringLength(10)]
    public string EmployeeStatusId { get; set; }

    [Required]
    [Column("employee_status_name")]
    [StringLength(21)]
    public string EmployeeStatusName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}