// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_holiday_date")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmHolidayDate
{
    [Key]
    [Column("holiday_id")]
    [StringLength(21)]
    public string HolidayId { get; set; }

    [Required]
    [Column("holiday_name")]
    [StringLength(100)]
    public string HolidayName { get; set; }

    [Column("holiday_date")]
    public DateTime HolidayDate { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("dt_etr", TypeName = "datetime")]
    public DateTime DtEtr { get; set; }

    [Required]
    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_update", TypeName = "datetime")]
    public DateTime DtUpdate { get; set; }

    [Required]
    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }
}