// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_inventory")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmInventory
{
    [Key]
    [Column("inventory_id")]
    [StringLength(20)]
    public string InventoryId { get; set; }

    [Required]
    [Column("inventory_name")]
    [StringLength(50)]
    public string InventoryName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}