// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_letter_type")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmLetterType
{
    [Key]
    [Column("letter_type_id")]
    [StringLength(21)]
    public string LetterTypeId { get; set; }

    [Required]
    [Column("letter_type_name")]
    [StringLength(50)]
    public string LetterTypeName { get; set; }

    [Required]
    [Column("mapping_id")]
    [StringLength(4)]
    public string MappingId { get; set; }

    [Column("status")]
    public sbyte Status { get; set; }
}