// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_letter_form")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmLetterForm
{
    [Key]
    [Column("letter_form_id")]
    [StringLength(21)]
    public string LetterFormId { get; set; }

    [Required]
    [Column("letter_form_name")]
    [StringLength(50)]
    public string LetterFormName { get; set; }

    [Column("mapping_id")]
    [StringLength(35)]
    public string MappingId { get; set; }

    [Required]
    [Column("department_id")]
    [StringLength(5)]
    public string DepartmentId { get; set; }

    [Required]
    [Column("letter_mapping")]
    [StringLength(10)]
    public string LetterMapping { get; set; }

    [Column("status")]
    public sbyte Status { get; set; }
}