// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_level")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmLevel
{
    [Key]
    [Column("level_id")]
    [StringLength(10)]
    public string LevelId { get; set; }

    [Required]
    [Column("level_name")]
    [StringLength(35)]
    public string LevelName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}