// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_married")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmMarried
{
    [Key]
    [Column("married_id")]
    [StringLength(5)]
    public string MarriedId { get; set; }

    [Required]
    [Column("married_name")]
    [StringLength(15)]
    public string MarriedName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}