// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models.Database.MySql;

[Table("tm_permission_type")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmPermissionType
{
    [Key]
    [Column("permission_type_id")]
    [StringLength(10)]
    public string PermissionTypeId { get; set; }

    [Required]
    [Column("permission_type")]
    [StringLength(21)]
    public string PermissionType { get; set; }

    [Column("status")]
    public int Status { get; set; }
}