// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_problem_category")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmProblemCategory
{
    [Key]
    [Column("problem_id")]
    [StringLength(21)]
    public string ProblemId { get; set; }

    [Column("problem_category")]
    [StringLength(50)]
    public string ProblemCategory { get; set; }

    [Column("problem_note")]
    [StringLength(100)]
    public string ProblemNote { get; set; }

    [Column("request_type")]
    public sbyte RequestType { get; set; }

    [Column("status")]
    public short Status { get; set; }
}