// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_reimbursment")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmReimbursment
{
    [Key]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Required]
    [Column("employee_first_name")]
    [StringLength(50)]
    public string EmployeeFirstName { get; set; }

    [Required]
    [Column("employee_last_name")]
    [StringLength(50)]
    public string EmployeeLastName { get; set; }

    [Required]
    [Column("department_id")]
    [StringLength(21)]
    public string DepartmentId { get; set; }

    [Column("amount_plafon")]
    [Precision(10, 0)]
    public decimal AmountPlafon { get; set; }
}