// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_request")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmRequest
{
    [Key]
    [Column("request_type_id")]
    [StringLength(10)]
    public string RequestTypeId { get; set; }

    [Required]
    [Column("request_name")]
    [StringLength(15)]
    public string RequestName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}