// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_sisa_cuti")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmSisaCuti
{
    [Key]
    [Column("inisial_cuti_id")]
    [StringLength(20)]
    public string InisialCutiId { get; set; }

    [Required]
    [Column("employee_id")]
    [StringLength(21)]
    public string EmployeeId { get; set; }

    [Column("years")]
    [StringLength(10)]
    public string Years { get; set; }

    [Column("sisa_cuti_annual")]
    public float SisaCutiAnnual { get; set; }

    [Column("sisa_cuti_maternity")]
    public float SisaCutiMaternity { get; set; }

    [Column("sisa_cuti_long")]
    public float SisaCutiLong {  get; set; } 

    [Column("sisa_cuti_replacement")]
    public float SisaCutiReplacement { get; set; }

    [Required]
    [Column("status_cuti")]
    public int? StatusCuti { get; set; }
}