// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_studi")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmStudi
{
    [Key]
    [Column("studi_id")]
    [StringLength(21)]
    public string StudiId { get; set; }

    [Required]
    [Column("studi_name")]
    [StringLength(15)]
    public string StudiName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}