// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_type_cuti")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmTypeCuti
{
    [Key]
    [Column("type_cuti_id")]
    [StringLength(10)]
    public string TypeCutiId { get; set; }

    [Required]
    [Column("nama_cuti")]
    [StringLength(21)]
    public string NamaCuti { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}