// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_type_ins")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmTypeIn
{
    [Key]
    [Column("type_ins_id")]
    [StringLength(20)]
    public string TypeInsId { get; set; }

    [Required]
    [Column("type_ins_name")]
    [StringLength(20)]
    public string TypeInsName { get; set; }

    [Column("status")]
    public bool Status { get; set; }
}