// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendHrdAgro.Models;

[Table("tm_user_groups")]
[MySqlCharSet("latin1")]
[MySqlCollation("latin1_swedish_ci")]
public partial class TmUserGroup
{
    [Key]
    [Column("group_id")]
    [StringLength(5)]
    public string GroupId { get; set; }

    [Column("group_name")]
    [StringLength(50)]
    public string GroupName { get; set; }

    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("status")]
    public sbyte? Status { get; set; }

    [Column("user_etr")]
    [StringLength(21)]
    public string UserEtr { get; set; }

    [Column("dt_etr")]
    public DateOnly? DtEtr { get; set; }

    [Column("user_update")]
    [StringLength(21)]
    public string UserUpdate { get; set; }

    [Column("dt_update")]
    public DateOnly? DtUpdate { get; set; }
}